version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - HOST_PUBLIC_DIR=/app/public
      - LLM_PROVIDER=OPENAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWELVE_LABS_API_KEY=${TWELVE_LABS_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGGRAPH_UI_ENABLED=true
    volumes:
      - ./public:/app/public
    ports:
      - "8001:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["uvicorn", "jockey.app:app", "--host", "0.0.0.0", "--port", "8000"]